workspace:
  base: /drone
  path: src/github.com/fusionapp/catcher-in-the-rye
pipeline:
  restore_cache:
    image: plugins/s3-cache
    pull: true
    endpoint: https://s3.amazonaws.com
    root: /drone-cache-fusionapp-useast
    restore: true
    mount:
      - stack
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
    when:
      event:
        - push
        - pull_request
        - tag
  stack-build:
    image: fusionapp/debian-stack
    pull: true
    commands:
      - stack --stack-root $PWD/stack setup
      - stack --stack-root $PWD/stack build --test
    when:
      event:
        - push
        - pull_request
        - tag
  stack-docker:
    image: fusionapp/debian-stack
    pull: true
    commands:
      - mkdir -p image/usr/local/bin
      - cp Dockerfile image
      - stack --stack-root $PWD/stack --local-bin-path $PWD/image/usr/local/bin build --copy-bins
    when:
      event: push
      branch: master
  rebuild_cache:
    image: plugins/s3-cache
    pull: true
    endpoint: https://s3.amazonaws.com
    root: /drone-cache-fusionapp-useast
    rebuild: true
    mount:
      - stack
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
    when:
      event: push
      branch:
        - master
  flush_cache:
    image: plugins/s3-cache
    pull: true
    endpoint: https://s3.amazonaws.com
    root: /drone-cache-fusionapp-useast
    flush: true
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
    when:
      event: push
      branch:
        - master
  publish:
    image: plugins/ecr
    context: image
    dockerfile: image/Dockerfile
    region: eu-west-1
    registry: 801493518741.dkr.ecr.eu-west-1.amazonaws.com
    repo: 801493518741.dkr.ecr.eu-west-1.amazonaws.com/catcher-in-the-rye
    tags:
      - ${DRONE_BRANCH}
      - git-${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: master
    secrets:
      - ecr_access_key
      - ecr_secret_key
  deploy:
    image: peloton/drone-rancher
    url: https://rancher.fusionapp.com
    service: catcher-in-the-rye/catcher-in-the-rye
    docker_image: 801493518741.dkr.ecr.eu-west-1.amazonaws.com/catcher-in-the-rye:git-${DRONE_COMMIT_SHA}
    start_first: false
    confirm: true
    timeout: 240
    when:
      event: push
      branch: master
    secrets:
      - source: rancher_nonprod_access_key
        target: rancher_access_key
      - source: rancher_nonprod_secret_key
        target: rancher_secret_key
  slack:
    image: plugins/slack
    secrets:
      - slack_webhook
    when:
      status:
        - success
        - failure
  slack_production:
    image: plugins/slack
    secrets:
      - slack_webhook
    channel: production
    when:
      event: push
      branch: master
      status:
        - success
        - failure
branches:
  - master
  - staging
  - trying
